# Generated by Django 3.0.2 on 2020-02-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190927_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow_set',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
